### ISSUE TITLE
Policy Compiler composition fails for doubly-nested non-optional match rules.

### ISSUE THREAD

**Issue by seirl** [cel-expr/cel-go#1087]
**Describe the bug**
When the policy compiler has a doubly-nested match rule in which the output is not optional, the composer thinks that the innermost nested rule has an optional type.

**Minimal reproducible example 1**

```yaml
rule:
  match:
    - condition: "1 > 0"
      rule:
        match:
          - rule:
              match:
                - output: "1002"

    - output: "1003"
```

Output:

```
ERROR: <input>:1:1: found no matching overload for '_?_:_' applied to '(bool, optional_type(int), int)'
 | true
 | ^
```

Expected: This should compile properly and return something equivalent to:

```
1 > 0 ? 1002 : 1003
```

**Minimal reproducible example 2**

```yaml
rule:
  match:
    - condition: "1 > 0"
      rule:
        match:
          - condition: "42 > 43"
            output: "1001"

          - rule:
              match:
                - output: "1002"

    - output: "1003"
```

Output:

```
ERROR: <input>:1:1: found no matching overload for '_?_:_' applied to '(bool, optional_type(int), int)'
 | true
 | ^
```

Expected: This should compile properly and return something equivalent to:

```
1 > 0 ? (42 > 43 ? 1001 : 1002) : 1003
```
