### ISSUE TITLE
[Policy Compiler] Surface type-mismatches error in a more readable fashion

### ISSUE THREAD

**Issue by l46kok** [cel-expr/cel-go#973]
Policy compiler will fail to type-check the composed policies (expectedly) if their output types are different. Example:

```
name: foo_policy
rule:
    match:
       - condition: x
         output: "error"
       - output: true
```

```
Compile() failed: ERROR: testdata/nested_rule/policy.yaml:-1:0: found no matching overload for '_?_:_' applied to '(bool, map(string, bool), string)'
```

We should try to raise this error in a more readable fashion, and ideally with the source positions wrt/ yaml. 

(xref b/350064634 for Java impl)
